export const ROUTES = {
  home: '/',
  login: '/login',
  register: '/register',
  app: '/app',
  profile: '/app/profile',
  changePassword: '/app/change-password',
  patientBook: '/app/patient/bookings/new',
  patientAppointments: '/app/patient/appointments',
  patientHistory: '/app/patient/history',
  patientDeposit: '/app/patient/deposit',
  patientLabResults: '/app/patient/lab-results',
  patientReviews: '/app/patient/reviews',
  doctorSchedule: '/app/doctor/schedule',
  doctorPatientHistory: '/app/doctor/patient-history',
  doctorExamination: (appointmentId) => `/app/doctor/schedule/${appointmentId}/examination`,
  adminTimeslots: '/app/admin/timeslots',
  adminTimeSlotCapacity: '/app/admin/timeslot-capacity',
  adminDepositConfig: '/app/admin/deposit-config',
  adminStatistics: '/app/admin/statistics',
  adminDoctors: '/app/admin/doctors',
  adminSpecialties: '/app/admin/specialties',
  adminNotifications: '/app/admin/notifications',
  adminUnits: '/app/admin/units',
  adminMedicineCategories: '/app/admin/medicine-categories',
  adminMedicines: '/app/admin/medicines',
}
